// ============================================
// test/home-ui-test.js —— 首页两栏卡片 UI 交互测试（jsdom 实测）
// 验证：默认经典卡+S、点卡片切换玩法栏、每栏各自记住规格（互不串扰）、
//       卡内创建/人机按钮按所点栏的玩法+规格开局、加入房间用当前选中栏
// 用法：node test/home-ui-test.js
// 说明：client.js 是严格模式 + 顶层 init，state 在 eval 作用域内取不到，
//       所以被测源码和测试代码合并成一段脚本一次 eval（同一作用域）。
// ============================================
'use strict';
const { JSDOM } = require('jsdom');
const fs = require('fs');

const html = fs.readFileSync('public/index.html', 'utf8');
const wsSrc = fs.readFileSync('public/ws.js', 'utf8');
const sharedSrc = fs.readFileSync('public/shared.js', 'utf8');
const clientSrc = fs.readFileSync('public/client.js', 'utf8');

const dom = new JSDOM(html, { url: 'http://localhost:3000/', runScripts: 'outside-only', pretendToBeVisual: true });
const win = dom.window;
win.WebSocket = require('ws').WebSocket; // init 里 WSClient 会真实连接本地服务器
win.matchMedia = function () { // jsdom 不提供 matchMedia，给个最小实现
  return { matches: false, addEventListener: function () {}, removeEventListener: function () {} };
};

// 测试代码与被测源码同一 eval 作用域：能直接访问 state，拦截 emit 记录开局参数
const testSrc = [
  'window.__uiTest = function () {',
  '  var passed = 0, failed = 0, lines = [], emits = [];',
  '  function check(name, cond) {',
  '    if (cond) { passed++; lines.push("  ✓ " + name); }',
  '    else { failed++; lines.push("  ✗ " + name); }',
  '  }',
  '  function activeMode() { var c = document.querySelector(".mode-card.active"); return c ? c.dataset.mode : null; }',
  '  function activeSpec() { var b = document.querySelector(".spec-btn.active"); return b && b.dataset.spec; }',
  '  function lastEmit() { return emits[emits.length - 1]; }',
  '  state.socket.emit = function (ev, data) { emits.push({ ev: ev, data: data }); };',
  '',
  '  // ===== 1. 默认状态：经典卡 + S =====',
  '  lines.push("1. 默认状态");',
  '  check("经典卡片默认选中", activeMode() === "classic");',
  '  check("规格默认 S 高亮", activeSpec() === "S");',
  '  check("帮助文字是经典", document.getElementById("mode-help").textContent.indexOf("经典") !== -1);',
  '',
  '  // ===== 2. 点道具卡片：选中 + 规格自动切道具默认 M =====',
  '  lines.push("2. 点道具卡片");',
  '  document.querySelector(".mode-card[data-mode=\\"props\\"]").click();',
  '  check("道具卡片选中", activeMode() === "props");',
  '  check("经典卡片取消选中", !document.querySelector(".mode-card[data-mode=\\"classic\\"]").classList.contains("active"));',
  '  check("规格自动换成道具默认 M", activeSpec() === "M");',
  '  check("帮助文字是道具版", document.getElementById("mode-help").textContent.indexOf("道具版") !== -1);',
  '',
  '  // ===== 2.5 规则弹窗两栏：默认经典栏，切道具栏有 6 个道具条目 =====',
  '  lines.push("2.5 规则弹窗两栏");',
  '  document.getElementById("btn-rules").click();',
  '  check("规则弹窗打开", !document.getElementById("rules-modal").classList.contains("hidden"));',
  '  check("默认展示经典栏", !document.getElementById("rules-pane-classic").classList.contains("hidden") && document.getElementById("rules-pane-props").classList.contains("hidden"));',
  '  check("经典栏有游戏目标（基础规则）", document.getElementById("rules-pane-classic").textContent.indexOf("游戏目标") !== -1);',
  '  document.querySelector(".rules-tab[data-tab=\\"props\\"]").click();',
  '  check("切道具栏后经典栏隐藏", document.getElementById("rules-pane-classic").classList.contains("hidden"));',
  '  check("道具栏有 6 个道具条目", document.querySelectorAll("#rules-pane-props .rules-list li").length === 6);',
  '  check("道具栏含金币经济", document.getElementById("rules-pane-props").textContent.indexOf("6 金币") !== -1);',
  '  check("道具栏不重复基础规则（无「游戏目标」）", document.getElementById("rules-pane-props").textContent.indexOf("游戏目标") === -1);',
  '  document.getElementById("btn-rules-close").click();',
  '  check("点「知道了」弹窗关闭", document.getElementById("rules-modal").classList.contains("hidden"));',
  '',
  '  // ===== 3. 道具栏改规格 L：存入 bp_spec_props =====',
  '  lines.push("3. 道具栏改规格");',
  '  document.querySelector(".spec-btn[data-spec=\\"L\\"]").click();',
  '  check("道具栏点 L 后高亮", activeSpec() === "L");',
  '  check("存入 bp_spec_props", window.localStorage.getItem("bp_spec_props") === "L");',
  '',
  '  // ===== 4. 切回经典卡：规格自动换回经典默认 S =====',
  '  lines.push("4. 切回经典卡片");',
  '  document.querySelector(".mode-card[data-mode=\\"classic\\"]").click();',
  '  check("经典卡片重新选中", activeMode() === "classic");',
  '  check("规格自动换回经典默认 S", activeSpec() === "S");',
  '',
  '  // ===== 5. 经典栏改 L → 切道具：还是道具栏自己的 L（互不串扰） =====',
  '  lines.push("5. 两栏规格互不串扰");',
  '  document.querySelector(".spec-btn[data-spec=\\"L\\"]").click();',
  '  check("经典栏点 L 后高亮", activeSpec() === "L");',
  '  check("存入 bp_spec_classic", window.localStorage.getItem("bp_spec_classic") === "L");',
  '  document.querySelector(".mode-card[data-mode=\\"props\\"]").click();',
  '  check("切道具后规格仍是道具栏的 L", activeSpec() === "L");',
  '  document.querySelector(".mode-card[data-mode=\\"classic\\"]").click();',
  '  check("切回经典规格仍是经典栏的 L", activeSpec() === "L");',
  '',
  '  // ===== 6. 创建/人机按钮（地图选择下方，不在卡片框里）：按当前选中栏开局 =====',
  '  lines.push("6. 创建/人机按钮（地图选择下方）");',
  '  check("按钮不在卡片框里", document.querySelector(".mode-card .mode-create") === null && document.querySelector(".home-actions .mode-create") !== null);',
  '  emits = [];',
  '  document.querySelector(".mode-card[data-mode=\\"props\\"]").click(); // 先选中道具栏',
  '  document.querySelector(".mode-create").click();',
  '  check("道具栏下「创建房间」emit 玩法 props", lastEmit().data.mode === "props");',
  '  check("道具栏下「创建房间」emit 规格 L（道具栏记忆）", lastEmit().data.boardSize === "L");',
  '  document.querySelector(".mode-card[data-mode=\\"classic\\"]").click(); // 切回经典栏',
  '  document.querySelector(".mode-ai").click();',
  '  check("经典栏下「人机对战」emit 玩法 classic", lastEmit().data.mode === "classic");',
  '  check("经典栏下「人机对战」emit 规格 L（经典栏记忆）", lastEmit().data.boardSize === "L");',
  '',
  '  // ===== 7. 加入房间按钮：用当前选中栏的玩法+规格 =====',
  '  lines.push("7. 加入房间按钮");',
  '  emits = [];',
  '  document.querySelector(".mode-card[data-mode=\\"props\\"]").click(); // 选中道具栏',
  '  document.getElementById("room-input").value = "1234";',
  '  document.getElementById("btn-join").click();',
  '  check("加入房间 emit 玩法 props", lastEmit().data.mode === "props");',
  '  check("加入房间 emit 规格 L", lastEmit().data.boardSize === "L");',
  '  check("加入房间 emit 房间号", lastEmit().data.roomId === "1234");',
  '',
  '  // ===== 8. 道具选区模式下右键 = 取消选中（而不是标记） =====',
  '  lines.push("8. 道具选区右键取消");',
  '  state.seat = 0;',
  '  state.spectator = false;',
  '  state.over = false;',
  '  state.enemyShotsReceived = [];',
  '  state.marks = {};',
  '  var enemyTd = document.querySelector("#enemy-board td");', // init 已给对手棋盘绑好右键处理器
  '  state.itemPick = { itemId: "sonar" };',
  '  enemyTd.dispatchEvent(new window.MouseEvent("contextmenu", { bubbles: true, cancelable: true }));',
  '  check("选区模式下右键取消道具选中", state.itemPick === null);',
  '  check("取消时没有误标到棋盘", Object.keys(state.marks).length === 0);',
  '  state.itemPick = null;',
  '  enemyTd.dispatchEvent(new window.MouseEvent("contextmenu", { bubbles: true, cancelable: true }));',
  '  check("非选区模式右键标注机身", state.marks["0,0"] === "body");',
  '  enemyTd.dispatchEvent(new window.MouseEvent("contextmenu", { bubbles: true, cancelable: true }));',
  '  check("再右键一次取消标注", state.marks["0,0"] === undefined);',
  '',
  '  // ===== 8.5 标注放宽：吞噬者摧毁的格、毁灭菇冻结的格都能标 =====',
  '  lines.push("8.5 吞噬摧毁格/冻结格可标注");',
  '  state.enemyShotsReceived = [{ row: 1, col: 1, result: "empty" }];',
  '  var tdRevealed = document.querySelector("#enemy-board td[data-row=\\"1\\"][data-col=\\"1\\"]");',
  '  tdRevealed.dispatchEvent(new window.MouseEvent("contextmenu", { bubbles: true, cancelable: true }));',
  '  check("已揭示格右键标注被拒", state.marks["1,1"] === undefined);',
  '  state.enemyShotsReceived.push({ row: 2, col: 2, result: "destroyed" });', // 吞噬者摧毁：内容保密算未揭示
  '  var tdDestroyed = document.querySelector("#enemy-board td[data-row=\\"2\\"][data-col=\\"2\\"]");',
  '  tdDestroyed.dispatchEvent(new window.MouseEvent("contextmenu", { bubbles: true, cancelable: true }));',
  '  check("吞噬摧毁格可以标注", state.marks["2,2"] === "body");',
  '  renderBattleBoards();',
  '  var tdD2 = document.querySelector("#enemy-board td[data-row=\\"2\\"][data-col=\\"2\\"]");',
  '  check("吞噬摧毁格渲染出标记绿框", /cell-mark-body/.test(tdD2.className));',
  '  state.enemyShotsReceived.push({ row: 3, col: 3, result: "head", destroyed: true });', // 吞噬命中机头：已发现
  '  var tdHead = document.querySelector("#enemy-board td[data-row=\\"3\\"][data-col=\\"3\\"]");',
  '  tdHead.dispatchEvent(new window.MouseEvent("contextmenu", { bubbles: true, cancelable: true }));',
  '  check("吞噬命中的机头不能标（视为已发现）", state.marks["3,3"] === undefined);',
  '  state.frozenCells = [{ row: 4, col: 4, owner: 0, expiry: 1 }];',
  '  var tdFrozen = document.querySelector("#enemy-board td[data-row=\\"4\\"][data-col=\\"4\\"]");',
  '  tdFrozen.dispatchEvent(new window.MouseEvent("contextmenu", { bubbles: true, cancelable: true }));',
  '  check("冻结格可以标注", state.marks["4,4"] === "body");',
  '  renderBattleBoards();',
  '  var tdF2 = document.querySelector("#enemy-board td[data-row=\\"4\\"][data-col=\\"4\\"]");',
  '  check("冻结格渲染出标记绿框（与 ❄ 共存）", /cell-mark-body/.test(tdF2.className) && /cell-frozen/.test(tdF2.className));',
  '  state.frozenCells = [];',
  '  state.enemyShotsReceived = [];',
  '  state.marks = {};',
  '',
  '  // ===== 9. 回到菜单再重进：冻结标记不能丢（goBattle 不得清空 frozenCells） =====',
  '  lines.push("9. 重连后冻结标记保留");',
  '  function fireEvent(ev, data) {', // 直接触发 WSClient 已注册的事件回调（绕过被替换的 emit）
  '    var list = state.socket._handlers.get(ev);',
  '    if (list) list.slice().forEach(function (cb) { cb(data); });',
  '  }',
  '  var rec = {',
  '    roomId: "T123", seat: 0, name: "A", names: ["A", "B"], online: [true, true],',
  '    steps: [12, 12], score: [0, 0], mode: "props", boardSize: "M", coins: [5, 3],',
  '    headsLeft: [4, 3], deployConfirmed: [true, true], myPlanes: [],',
  '    myShotsReceived: [], enemyShotsReceived: [], sonarHistory: [],',
  '    frozenCells: [{ row: 3, col: 1, owner: 0, expiry: 20 }],',
  '    winner: null, winReason: null, rematchVotes: [false, false], isAI: false,',
  '    planes: null, phase: "battle"',
  '  };',
  '  fireEvent("reconnected", rec);',
  '  check("重连后 frozenCells 保留", state.frozenCells.length === 1);',
  '  var frozenTd = document.querySelector("#enemy-board td[data-row=\\"3\\"][data-col=\\"1\\"]");',
  '  check("重连后冻结格渲染 ❄", frozenTd && frozenTd.classList.contains("cell-frozen"));',
  '  // 再来一局（battleStart 新局）：冻结才清零',
  '  state.socket._handlers.get("battleStart").slice().forEach(function (cb) { cb({ names: ["A", "B"], steps: [0, 0], score: [0, 0], online: [true, true], mode: "props", boardSize: "M", coins: [8, 8] }); });',
  '  check("开新一局（battleStart）冻结清零", state.frozenCells.length === 0);',
  '',
  '  // ===== 10. 声呐渲染：数字在中心格 + 3×3 区域外圈金色边框 =====',
  '  lines.push("10. 声呐区域框与中心数字");',
  '  state.sonarResults = [{ row: 2, col: 3, count: 4 }];',
  '  renderBattleBoards();',
  '  var sonarCenter = document.querySelector("#enemy-board td[data-row=\\"3\\"][data-col=\\"4\\"]");',
  '  check("声呐数字显示在区域中心格", sonarCenter && sonarCenter.textContent === "4" && sonarCenter.classList.contains("cell-sonar"));',
  '  var sonarCorner = document.querySelector("#enemy-board td[data-row=\\"2\\"][data-col=\\"3\\"]");',
  '  check("区域外圈格有金色边框（左上角）", sonarCorner && sonarCorner.style.boxShadow.indexOf("inset") !== -1 && sonarCorner.style.boxShadow.indexOf("f6c945") !== -1);',
  '  check("中心格无边框（只标数字）", sonarCenter.style.boxShadow === "");',
  '  var sonarOut = document.querySelector("#enemy-board td[data-row=\\"1\\"][data-col=\\"3\\"]");',
  '  check("区域外没有边框", sonarOut.style.boxShadow === "");',
  '  state.sonarResults = [];',
  '',
  '  // ===== 10. 毁灭菇选区：十字轮廓框（4 臂各 3 条外缘线，中心无线条 → 浅金填充锚点格） =====',
  '  lines.push("10. 毁灭菇十字轮廓");',
  '  state.boardSize = "M"; state.seat = 0; state.spectator = false; state.over = false;',
  '  state.revealedPlanes = null; state.myPlanes = []; state.myShotsReceived = [];',
  '  state.enemyShotsReceived = []; state.sonarResults = []; state.frozenCells = [];',
  '  state.marks = {}; state.steps = [0, 0];',
  '  state.itemPick = { itemId: "doom" }; state.pickCells = crossKeys(5, 5); state.pickHover = [];',
  '  renderBattleBoards();',
  '  function doomBs(r, c) { return document.querySelector("#enemy-board td[data-row=\\"" + r + "\\"][data-col=\\"" + c + "\\"]").style.boxShadow || ""; }',
  '  function doomCls(r, c) { return document.querySelector("#enemy-board td[data-row=\\"" + r + "\\"][data-col=\\"" + c + "\\"]").className; }',
  '  check("中心格无框线（内部无线条）", doomBs(5, 5) === "");',
  '  check("中心格走浅金填充（cell-pick-anchor）而非 outline 方框", doomCls(5, 5).indexOf("cell-pick-anchor") !== -1 && !/(^|\\s)cell-pick(-hover)?($|\\s)/.test(doomCls(5, 5)));',
  '  check("上臂格 3 条外缘线（顶 + 左右）", doomBs(4, 5).indexOf("inset 0 3px 0 0") !== -1 && doomBs(4, 5).indexOf("inset 3px 0 0 0") !== -1 && doomBs(4, 5).indexOf("inset -3px 0 0 0") !== -1);',
  '  check("下臂格 3 条外缘线（底 + 左右）", doomBs(6, 5).indexOf("inset 0 -3px 0 0") !== -1 && doomBs(6, 5).indexOf("inset 3px 0 0 0") !== -1 && doomBs(6, 5).indexOf("inset -3px 0 0 0") !== -1);',
  '  check("左臂格 3 条外缘线（顶 + 底 + 左）", doomBs(5, 4).indexOf("inset 0 3px 0 0") !== -1 && doomBs(5, 4).indexOf("inset 0 -3px 0 0") !== -1 && doomBs(5, 4).indexOf("inset 3px 0 0 0") !== -1);',
  '  check("右臂格 3 条外缘线（顶 + 底 + 右）", doomBs(5, 6).indexOf("inset 0 3px 0 0") !== -1 && doomBs(5, 6).indexOf("inset 0 -3px 0 0") !== -1 && doomBs(5, 6).indexOf("inset -3px 0 0 0") !== -1);',
  '  check("十字外的角格无框", (doomBs(4, 4).indexOf("f59e0b") === -1));',
  '  check("更远的区域外格无框", (doomBs(3, 4).indexOf("f59e0b") === -1));',
  '  state.itemPick = null; state.pickCells = []; state.pickHover = [];',
  '',
  '  // ===== 10.5 3×3 区域型道具预览：外圈 12 条边 + 内部无线条 + 中心浅金填充 =====',
  '  lines.push("10.5 3×3 区域轮廓预览");',
  '  state.itemPick = { itemId: "sonar" }; state.pickCells = regionKeys(2, 3); state.pickHover = [];',
  '  renderBattleBoards();',
  '  function sonarBs(r, c) { return document.querySelector("#enemy-board td[data-row=\\"" + r + "\\"][data-col=\\"" + c + "\\"]").style.boxShadow || ""; }',
  '  function sonarCls(r, c) { return document.querySelector("#enemy-board td[data-row=\\"" + r + "\\"][data-col=\\"" + c + "\\"]").className; }',
  '  check("锚点格（左上角）有 2 条外圈边（顶 + 左）", sonarBs(2, 3).indexOf("inset 0 3px 0 0") !== -1 && sonarBs(2, 3).indexOf("inset 3px 0 0 0") !== -1);',
  '  check("顶边中间格只有顶线（无底线）", sonarBs(2, 4).indexOf("inset 0 3px 0 0") !== -1 && sonarBs(2, 4).indexOf("inset 0 -3px 0 0") === -1);',
  '  check("底边格有底线", sonarBs(4, 4).indexOf("inset 0 -3px 0 0") !== -1);',
  '  check("左列边格有左边线", sonarBs(3, 3).indexOf("inset 3px 0 0 0") !== -1);',
  '  check("右列边格有右边线", sonarBs(3, 5).indexOf("inset -3px 0 0 0") !== -1);',
  '  check("区域内部格无线条", sonarBs(3, 4) === "");',
  '  check("内部格也没有 cell-pick outline（不再逐格描边）", !/(^|\\s)cell-pick(-hover)?($|\\s)/.test(sonarCls(3, 4)));',
  '  check("区域外格无线条", sonarBs(1, 3) === "");',
  '  check("中心格有浅金填充 class", sonarCls(3, 4).indexOf("cell-pick-anchor") !== -1);',
  '  check("左上角锚点格不再浅金填充", sonarCls(2, 3).indexOf("cell-pick-anchor") === -1);',
  '  // 区域边缘格上有「机身」标记：绿框拼进内联阴影，预览框线不遮标记',
  '  state.marks["2,3"] = "body";',
  '  renderBattleBoards();',
  '  check("边缘标记格的绿框拼进内联阴影（金线 + 绿框并存）", sonarBs(2, 3).indexOf("f59e0b") !== -1 && sonarBs(2, 3).indexOf("66bb6a") !== -1);',
  '  // 区域内部格（非轮廓格）：无内联阴影，标记绿框走 class 正常生效',
  '  state.marks["3,4"] = "body";',
  '  renderBattleBoards();',
  '  check("区域内部标记格绿框正常（无内联阴影时 class 生效）", sonarBs(3, 4) === "" && /cell-mark-body/.test(sonarCls(3, 4)));',
  '  state.marks["2,3"] = undefined; state.marks["3,4"] = undefined;',
  '  delete state.marks["2,3"]; delete state.marks["3,4"];',
  '  renderBattleBoards();',
  '  check("清除标记后绿框消失", sonarBs(2, 3).indexOf("66bb6a") === -1 && /cell-mark-body/.test(sonarCls(3, 4)) === false);',
  '  // 悬停预览（pickCells 空）：同样的外轮廓 + 内部无线条',
  '  state.itemPick = { itemId: "devour" }; state.pickCells = []; state.pickHover = regionKeys(5, 6);',
  '  renderBattleBoards();',
  '  check("悬停预览也画外轮廓（顶边）", sonarBs(5, 7).indexOf("inset 0 3px 0 0") !== -1);',
  '  check("悬停预览内部无线条", sonarBs(6, 7) === "");',
  '  state.itemPick = null; state.pickCells = []; state.pickHover = [];',
  '',
  '  // ===== 11. 道具按钮金币置灰：金币不够买不起的道具禁用 =====',
  '  lines.push("11. 道具按钮置灰");',
  '  state.mode = "props";',
  '  state.coins = [3, 8]; state.steps = [0, 0]; state.spectator = false; state.over = false;',
  '  state.itemPick = null;',
  '  updateItemButtons();',
  '  function btn(itemId) { return document.querySelector(".item-btn[data-item=\\"" + itemId + "\\"]"); }',
  '  check("3 金币买不起声呐（4 金币）", btn("sonar").disabled === true);',
  '  check("3 金币买不起毁灭菇（8 金币）", btn("doom").disabled === true);',
  '  check("3 金币买得起吞噬者（3 金币）", btn("devour").disabled === false);',
  '  check("3 金币买不起探测者（4 金币）", btn("pro").disabled === true);',
  '  check("我上一步刚走完（steps 1:0）时全部禁用", (function () { state.steps = [1, 0]; updateItemButtons(); return btn("sonar").disabled && btn("doom").disabled; })());',
  '',
  '  // ===== 12. 金币三处显示：道具栏 + 我方信息卡 + 对方信息卡 =====',
  '  lines.push("12. 金币三处显示");',
  '  state.mode = "props";',
  '  state.coins = [7, 4];',
  '  state.seat = 0;',
  '  state.spectator = false;',
  '  updateBattlePanels();',
  '  check("道具栏金币 = 7", document.getElementById("panel-my-coins").textContent === "7");',
  '  check("我方信息卡金币 = 7", document.getElementById("panel-my-coins-info").textContent === "7");',
  '  check("我方信息卡金币行可见", document.getElementById("panel-my-coins-info-row").className.indexOf("hidden") === -1);',
  '  check("对方信息卡金币 = 4", document.getElementById("panel-enemy-coins").textContent === "4");',
  '  state.mode = "classic";',
  '  updateBattlePanels();',
  '  check("经典模式金币行隐藏", document.getElementById("panel-my-coins-info-row").className.indexOf("hidden") !== -1);',
  '',
  '  // ===== 13. 对战界面规则按钮：优先显示当前模式的规则栏 =====',
  '  lines.push("13. 对战规则按钮");',
  '  state.mode = "props";',
  '  document.getElementById("btn-battle-rules").click();',
  '  check("道具版点开规则弹窗", !document.getElementById("rules-modal").classList.contains("hidden"));',
  '  check("默认切到道具模式栏", document.querySelector(".rules-tab[data-tab=\\"props\\"]").classList.contains("active"));',
  '  document.getElementById("btn-rules-close").click();',
  '  state.mode = "classic";',
  '  document.getElementById("btn-battle-rules").click();',
  '  check("经典版点开默认经典栏", document.querySelector(".rules-tab[data-tab=\\"classic\\"]").classList.contains("active"));',
  '  document.getElementById("btn-rules-close").click();',
  '',
  '  return { passed: passed, failed: failed, lines: lines };',
  '};'
].join('\n');

try {
  win.eval(wsSrc + '\n' + sharedSrc + '\n' + clientSrc + '\n' + testSrc);
} catch (e) {
  console.error('client.js 执行异常:', e.message);
  console.error((e.stack || '').split('\n').slice(0, 5).join('\n'));
  process.exit(1);
}

const result = win.__uiTest();
console.log(result.lines.join('\n'));
console.log('\n结果: ' + result.passed + ' 通过, ' + result.failed + ' 失败');
process.exitCode = result.failed ? 1 : 0;
setTimeout(function () { process.exit(process.exitCode); }, 500); // 等 ws 连接回收
